version: "3"
services:
  api:
    build: .
    depends_on:
      - postgres
    ports:
      - 9090:9090
    command:
      - alembic revision --autogenerate -m "Init"
      - alembic current
    #env_file:
    #  - ./.env
    environment:
      - DATABASE_HOSTNAME=postgres
      - DATABASE_PORT=5432
      - DATABASE_PASSWORD=password123
      - DATABASE_NAME=fastapi
      - DATABASE_USERNAME=postgres
      - SECURITY_KEY="HELLO"
      - ALGORITHM="HS256"
      - ACCESS_TOKEN_EXPIRE_MINUTES=120
  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password123
      - POSTGRES_DB=fastapi
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db:




